server:
  port: 3344

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          #github上面的仓库名称
          uri: https://github.com/13501001225/springcloud-config.git
          #搜索目录
          search-paths:
            - springcloud-config
      #读取分支
      label: master
  #rabbitmq相关配置
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
#暴露bus刷新端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"