server:
  port: 8004
spring:
  application:
    name: cloud-provider-payment
    cloud:
        zookeeper:
          # 默认localhost:2181
          connect-string: cloud101:2181
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: 123456
eureka:
  client:
    #表示将自己注册进EurekaServer服务器
    register-with-eureka: true
    #是否从EurekaServer抓取自己注册的信息，默认为true。集群必须设置为true，才能配合ribbon使用
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 1 #Eureka客户端向服务端发送心跳的时间间隔，单位为秒
    lease-expiration-duration-in-seconds: 2 #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gw.springcloud.entities


